name = "angular-ecommerce-app"
compatibility_date = "2026-08-15"
workers_dev = true

[assets]
directory = "./dist/angular-ecommerce-app/browser"
not_found_handling = "single-page-application"

[build]
command = "npm ci && npm run build"
cwd = "./"
